services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    links:
      - db
  db:
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
