[package]
name = "zhongcaoyaominglu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
diesel = { version = "1.4.4", features = ["mysql"] }
dotenv = "0.15.0"
