//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "chinese_medicine_nature_nature")]
pub struct Model {
    #[sea_orm(column_name = "chineseMedicineId", primary_key, auto_increment = false)]
    pub chinese_medicine_id: i32,
    #[sea_orm(column_name = "natureId", primary_key, auto_increment = false)]
    pub nature_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chinese_medicine::Entity",
        from = "Column::ChineseMedicineId",
        to = "super::chinese_medicine::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ChineseMedicine,
    #[sea_orm(
        belongs_to = "super::nature::Entity",
        from = "Column::NatureId",
        to = "super::nature::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Nature,
}

impl Related<super::chinese_medicine::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChineseMedicine.def()
    }
}

impl Related<super::nature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nature.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
