//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "chinese_medicine")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_name = "categoryId")]
    pub category_id: Option<i32>,
    #[sea_orm(column_name = "dateCreate_time")]
    pub date_create_time: DateTime,
    #[sea_orm(column_name = "dateUpdate_time")]
    pub date_update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::category::Entity",
        from = "Column::CategoryId",
        to = "super::category::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Category,
    #[sea_orm(has_many = "super::chinese_medicine_images_image::Entity")]
    ChineseMedicineImagesImage,
    #[sea_orm(has_many = "super::chinese_medicine_meridian_tropism_meridian_tropism::Entity")]
    ChineseMedicineMeridianTropismMeridianTropism,
    #[sea_orm(has_many = "super::chinese_medicine_nature_nature::Entity")]
    ChineseMedicineNatureNature,
    #[sea_orm(has_many = "super::chinese_medicine_taste_taste::Entity")]
    ChineseMedicineTasteTaste,
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl Related<super::chinese_medicine_images_image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChineseMedicineImagesImage.def()
    }
}

impl Related<super::chinese_medicine_meridian_tropism_meridian_tropism::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChineseMedicineMeridianTropismMeridianTropism.def()
    }
}

impl Related<super::chinese_medicine_nature_nature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChineseMedicineNatureNature.def()
    }
}

impl Related<super::chinese_medicine_taste_taste::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChineseMedicineTasteTaste.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
