//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub mod prelude;

pub mod admin;
pub mod category;
pub mod category_bg_img;
pub mod category_closure;
pub mod chinese_medicine;
pub mod chinese_medicine_alias;
pub mod chinese_medicine_images_image;
pub mod chinese_medicine_meridian_tropism_meridian_tropism;
pub mod chinese_medicine_nature_nature;
pub mod chinese_medicine_taste_taste;
pub mod image;
pub mod meridian_tropism;
pub mod nature;
pub mod passage;
pub mod query_result_cache;
pub mod taste;
