//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::admin::Entity as Admin;
pub use super::category::Entity as Category;
pub use super::category_bg_img::Entity as CategoryBgImg;
pub use super::category_closure::Entity as CategoryClosure;
pub use super::chinese_medicine::Entity as ChineseMedicine;
pub use super::chinese_medicine_alias::Entity as ChineseMedicineAlias;
pub use super::chinese_medicine_images_image::Entity as ChineseMedicineImagesImage;
pub use super::chinese_medicine_meridian_tropism_meridian_tropism::Entity as ChineseMedicineMeridianTropismMeridianTropism;
pub use super::chinese_medicine_nature_nature::Entity as ChineseMedicineNatureNature;
pub use super::chinese_medicine_taste_taste::Entity as ChineseMedicineTasteTaste;
pub use super::image::Entity as Image;
pub use super::meridian_tropism::Entity as MeridianTropism;
pub use super::nature::Entity as Nature;
pub use super::passage::Entity as Passage;
pub use super::query_result_cache::Entity as QueryResultCache;
pub use super::taste::Entity as Taste;
