//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "taste")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_name = "dateCreate_time")]
    pub date_create_time: DateTime,
    #[sea_orm(column_name = "dateUpdate_time")]
    pub date_update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chinese_medicine_taste_taste::Entity")]
    ChineseMedicineTasteTaste,
}

impl Related<super::chinese_medicine_taste_taste::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChineseMedicineTasteTaste.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
